OIDC_PROVIDER_DOMAIN = "DOMAIN_PLACEHOLDER"
OIDC_PROVIDER_URI = f"{OIDC_PROVIDER_DOMAIN}/"
OIDC_PROVIDER_URL = f"https://{OIDC_PROVIDER_URI}"

CLIENT_ID = "CLIENT_ID_PLACEHOLDER"

TENANT_ID = "TENANT_ID_PLACEHOLDER"
